### ISSUE TITLE
Template inheritance broken in Symfony 4

### ISSUE THREAD

**Issue by curry684** [KnpLabs/KnpMenuBundle#376] opened 2017-12-18 22:43 UTC
On a fresh Symfony 4 Flex project the bundle is broken, as it cannot find the `knp_menu.html.twig` ancestor template its own templates derive from.

Reason is that `AddTemplatePathPass` depends on a pretty flakey way of adding the original templates to the Twig file loader. As the `twig.loader.filesystem` service is private by default on Symfony 4 the pass fails completely, yet silently, thereby causing that neither the bundle itself nor consumers can inherit from the base templates.

**Comment by stof** [comment] 2017-12-19 10:38
Duplicate of https://github.com/KnpLabs/KnpMenuBundle/issues/374

**Closed by stof** 2017-12-19 10:38 UTC
